title: Pascal Tech
description: 我们是设计者、开发者、也是运营者。

url: https://pascal-tech.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: Pascal_Tech
  twitter: Pascal_Tech
  facebook: 
  email: 

google_analytics: 
